name = "httpstatus-xyz-prod"
type = "webpack"
account_id = "5bb62796e4ac364a01fc43eba5da2b5d"
workers_dev = false
route = "httpstatus.xyz/*"
zone_id = "5a0317eca0e85fd48a8eb4ca880e99e2"

[site]
bucket = "./_site"
entry-point = "workers-site"